# Generated by Django 5.2.9 on 2025-12-25 13:06

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL-слаг')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('AC', 'Active')], default='DR', max_length=2, verbose_name='Статус')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['-publication_date'], name='posts_artic_publica_e645b6_idx')],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
